<section class="fechado">
    <table>
        <tr>
            <th>Energia</th>
            <td></td>
        </tr>
        <tr>
            <th>Vida</th>
            <td></td>
        </tr>
        <tr>
            <th>Dano</th>
            <td></td>
        </tr>
        <tr>
            <th>Chance de Crítico</th>
            <td></td>
        </tr>
        <tr>
            <th>Armadura</th>
            <td></td>
        </tr>
        <tr>
            <th>Reflexo</th>
            <td></td>
        </tr>
        <tr>
            <th>Velocidade</th>
            <td></td>
        </tr>
    </table>

    <h3>Pontos para distribuir: 0</h3>

    <table>
        <tr>
            <th>Vigor</th>
            <td></td>
            <td><button>+</button></td>
        </tr>
        <tr>
            <th>Vitalidade</th>
            <td></td>
            <td><button>+</button></td>
        </tr>
        <tr>
            <th>Força</th>
            <td></td>
            <td><button>+</button></td>
        </tr>
        <tr>
            <th>Sorte</th>
            <td></td>
            <td><button>+</button></td>
        </tr>
        <tr>
            <th>Resistência</th>
            <td></td>
            <td><button>+</button></td>
        </tr>
        <tr>
            <th>Destreza</th>
            <td></td>
            <td><button>+</button></td>
        </tr>
        <tr>
            <th>Agilidade</th>
            <td></td>
            <td><button>+</button></td>
        </tr>
    </table>
</section>